#coding: utf-8

'''
Tables des correspondances
	Le rang 0 correspond à la position de l’information dans la trame MAESTRO
	Le rang 1 correspond a l’intitulé publié sur le broker
	Le rang 2 (optionnel) permet de remplacer le code de la trame par une information texte correspondante
'''

RecuperoInfo=[
	[1,"Etat du poêle",[
		[0, "Eteint"],
		[1, "Controle du poele froid / chaud"],
		[2, "Clean Froid"],
		[3, "Load Froid"],
		[4, "Start 1 Froid"],
		[5, "Start 2 Froid"],
		[6, "Clean Chaud"],
		[7, "Load Chaud"],
		[8, "Start 1 chaud"],
		[9, "Start 2 chaud"],
		[10, "Stabilisation"],
		[11, "Puissance 1"],
		[12, "Puissance 2"],
		[13, "Puissance 3"],
		[14, "Puissance 4"],
		[15, "Puissance 5"],
		[30, "Mode diagnostique"],
		[31, "Marche"],
		[40, "Extinction"],
		[41, "Refroidissement en cours"],
		[42, "Nettoyage basse p."],
		[43, "Nettoyage haute p."],
		[44, "Debloquage vis sans fin"],
		[45, "AUTO ECO"],
		[46, "Standby"],
		[48, "Diagnostique"],
		[49, "CHARG. VIS SANS FIN"],
		[50, "Erreur A01 - Allumage rate"],
		[51, "Erreur A02 - Pas de flamme"],
		[52, "Erreur A03 - Surchauffe du reservoir"],
		[53, "Erreur A04 - Temperature des fumees trop haute"],
		[54, "Erreur A05 - Obstruction conduit - Vent"],
		[55, "Erreur A06 - Mauvais tirage"],
		[56, "Erreur A09 - Defaillance sonde de fumees"],
		[57, "Erreur A11 - Defaillance motoreducteur"],
		[58, "Erreur A13 - Temperature carte mere trop haute"],
		[59, "Erreur A14 - Defaut Active"],
		[60, "Erreur A18 - Temperature d’eau trop haute"],
		[61, "Erreur A19 - Defaut sonde température eau"],
		[62, "Erreur A20 - Defaut sonde auxiliaire"],
		[63, "Erreur A21 - Alarme pressostat"],
		[64, "Erreur A22 - Defaut sonde ambiante"],
		[65, "Erreur A23 - Defaut fermeture brasero"],
		[66, "Erreur A12 - Panne controleur motoreducteur"],
		[67, "Erreur A17 - Bourrage vis sans fin"],
		[69, "Attente Alarmes securite"],
		]],
	[2,"Etat du ventilateur d’ambiance",[
		[0, "Desactive"],
		[1, "Niveau 1"],
		[2, "Niveau 2"],
		[3, "Niveau 3"],
		[4, "Niveau 4"],
		[5, "Niveau 5"],
		[6, "Automatique"],
	]],
	[3,"Etat du ventilateur canalise 1",[
		[0, "Desactive"],
		[1, "Niveau 1"],
		[2, "Niveau 2"],
		[3, "Niveau 3"],
		[4, "Niveau 4"],
		[5, "Niveau 5"],
		[6, "Automatique"],
	]],
	[4,"Etat du ventilateur canalise 2",[
		[0, "Desactive"],
		[1, "Niveau 1"],
		[2, "Niveau 2"],
		[3, "Niveau 3"],
		[4, "Niveau 4"],
		[5, "Niveau 5"],
		[6, "Automatique"],
	]],
	[5,"Température des fumées"],
	[6,"Température ambiante"],
	[7,"Puffer Température"], # !=255 == Hydro
	[8,"Température chaudiére"],
	[9,"Température NTC3"], # !=255 == Hydro
	[10,"Etat de la bougie"],
	[11,"ACTIVE - Set"],
	[12,"RPM - Ventilateur fumées"],
	[13,"RPM - Vis sans fin - SET"],
	[14,"RPM - Vis sans fin - LIVE"],
	[15,"Valve 3 voies"], # 1= Sani !1= Risc ==Hydro
	[16,"Alimentation pompe"],
	[17,"Brazero",[
		[0, "OK"],
		[101, "Ouverture brazero"],
		[100, "Fermeture brazero"],
	]], # !==Matic
	[18,"Profile",[
		[0, "Manuel"],
		[1, "Dynamic"],
		[2, "Overnight"],
		[3, "Comfort"],
		[4, "Power 110%"],
		[10, "Mode Adaptatif"],
	]],
	[19,"Modbus address"],
	[20,"Etat du mode Active"], #0: Désactivé, 1: Activé
	[21,"ACTIVE - Live"],
	[22,"Mode de régulation",[
		[0, "Manuelle"],
		[1, "Dynamique"],
	]],
	[23,"Mode ECO"],
	[24,"Silence"],
	[25,"Mode Chronotermostato"],
	[26,"TEMP - Consigne"],
	[27,"TEMP - Boiler"],
	[28,"TEMP - Carte mère"],
	[29,"Puissance Active",[
		[11, "Puissance 1"],
		[12, "Puissance 2"],
		[13, "Puissance 3"],
		[14, "Puissance 4"],
		[15, "Puissance 5"],
	]],
	[32,"Heure du poêle (0-23)"],
	[33,"Minutes du poêle (0-59)"],
	[34,"Jour du poêle (1-31)"],
	[35,"Mois du poêle (1-12)"],
	[36,"Année du poêle"],
	[37,"Heures de fonctionnement total (s)"],
	[38,"Heures de fonctionnement en puissance 1 (s)"],
	[39,"Heures de fonctionnement en puissance 2 (s)"],
	[40,"Heures de fonctionnement en puissance 3 (s)"],
	[41,"Heures de fonctionnement en puissance 4 (s)"],
	[42,"Heures de fonctionnement en puissance 5 (s)"],
	[43,"Heures avant entretien"],
	[44,"Minutes avant extinction"],
	[45,"Nombre d’allumages"],
	[46,"Temperature active"],
	[47,"Sonde Pellet",[
		[0, "Sonde pas active"],
		[10, "Niveau suffisant"],
		[11, "Niveau presque vide"],
	]],
	[48,"Effet sonore"],
	[49,"Etat effets sonores"],
	[50,"Sleep"],
	[51,"Mode",[
		[0, "Hiver"],
		[1, "Ete"],
	]],
	[52,"Sonde wifi temperature 1"],
	[53,"Sonde wifi temperature 2"],
	[54,"Sonde wifi temperature 3"],
	[55,"Inconnu"], # !== Ne sait pas à quoi ça correspond
	[56,"Set Puffer"],
	[57,"Set Boiler"],
	[58,"Set Health"], # !==Hydro
	[59,"Température retour"],
	[60,"Antigele"],
]

RecuperoParametriExtra=[
	[0,"Inconnu"],
	[1,"Air"],
	[2,"Granules"],
	[3,"Inconnu"],
	[4,"Inconnu"],
	[5,"Inconnu"],
	[6,"Inconnu"],
	[7,"Inconnu"],
	[8,"Inconnu"],
	[9,"Inconnu"],
	[10,"Inconnu"],
	[11,"Inconnu"],
	[12,"Inconnu"],
	[13,"Inconnu"],
	[14,"Inconnu"],
	[15,"Inconnu"],
	[16,"Inconnu"],
	[17,"Inconnu"],
	[18,"Inconnu"],
	[19,"Inconnu"],
	[20,"Inconnu"],
	[21,"Inconnu"],
	[22,"Inconnu"],
	[23,"Inconnu"],
	[24,"Inconnu"],
	
]
